notifications:
  email: false
sudo: required
language: generic

services:
  - docker

script:
  - wget -O - http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/

before_deploy:
  - export RELEASE_PKG_FILE=$(ls qradiolink_*.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key: "df450d5c23e2439cf01e3df41ae783cadf109d55"
  skip_cleanup: true
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  overwrite: true
  on:
    tags: true
