notifications:
  email: false
sudo: required
language: generic

services:
  - docker

script:
  - wget -O - http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/

before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key: "544ee8e113651687e9232e4baa5ed78d48e706a5"
  skip_cleanup: true
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  overwrite: true
  on:
    tags: true
